install.packages("tidyverse")
install.packages("dataRetrieval")
install.packages("lubridate")
install.packages("viridis")
install.packages("learnr")
install.packages("nycflights13")
install.packages("Lahman")
