FROM rocker/binder:3.6.1
LABEL maintainer='Andrew Peter Moles'
USER root
COPY . ${HOME}
RUN chown -R ${NB_USER} ${HOME}
USER ${NB_USER}



RUN wget https://github.com/andrewmoles2/MyBinder-example/raw/master/DESCRIPTION && R -e "options(repos = list(CRAN = 'http://mran.revolutionanalytics.com/snapshot/2019-10-24/')); devtools::install_deps()"

RUN rm DESCRIPTION.1; exit 0
